# LOGIN RESTRICTIONS
PermitRootLogin no

# CONNECTION THROTTLING
# Maximum number of concurrent unauthenticated SSH connections.
# Syntax: MaxStartups start:rate:full
# - start = begin probabilistically dropping new connections.
# - rate  = initial drop probability (percent).
# - full  = reject all new unauthenticated connections.
# Example:
#   0-10 pending logins   -> accept all
#   11 pending logins     -> ~30% of new connections dropped
#   60 or more            -> reject all new connections
MaxStartups 10:30:60

# MAXIMUM NUMBER of simultaneous unauthenticated connections
# allowed from a single source IP address. Example for '1':
#       Login #1 -> allowed
#       Login #2 -> rejected
PerSourceMaxStartups 1

# Maximum time (in seconds) allowed for a client to complete
# authentication after establishing a TCP connection.
# If the client has not successfully authenticated within this time,
# the connection is closed.
LoginGraceTime 3

# Maximum number of authentication attempts allowed per connection.
# After this count of failed attempts, the connection is terminated.
MaxAuthTries 1

# Maximum number of SSH channels (shells, exec commands, tunnels,
# subsystems) that may be opened within a single authenticated SSH
# connection.
# This does NOT limit users to one login.
# It limits one login session to a single SSH channel.
# A second independent SSH login is still permitted.
MaxSessions 2
