login=YOUR_API_TOKEN
password='YOUR_API_TOKEN'
daemon=180 # Interval to refresh DNS-name in seconds
ssl=yes

# === === Provider-specific settings === ===

# = Cloudflare provider =
# protocol=cloudflare
# server=api.cloudflare.com
# zone=yourname.example.com

# = No-IP provider =
# protocol=noip
# server=dynupdate.no-ip.com
# protocol=noip
# server=dynupdate.no-ip.com

# = DuckDNS provider =
# protocol=duckdns
# Does not use `server`


# === === The DNS-name you are asking for === ===
requested-name.example.com
