# =====================================================================
# SYSTEM
# =====================================================================
CONTAINER_NAME="zeroviewer-server"
IMAGE_NAME="zeroviewer-ssh-server"

# =====================================================================
# NETWORK
# =====================================================================
EXTERNAL_SSH_PORT=9022
INTERNAL_SSH_PORT=22

# =====================================================================
# USERS AND GROUPS
# =====================================================================
CLIENTS_GROUP="zero_clients"
OPERATORS_GROUP="zero_operators"

CLIENTS_DB_PATH=passwords/clients.txt
OPERATORS_DB_PATH=passwords/operators.txt

SERVER_CLIENTS_DB_PATH=/etc/ssh/auth_db/clients.txt
SERVER_OPERATORS_DB_PATH=/etc/ssh/auth_db/operators.txt
